name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'kubernetes/**'
      - '.github/**'

permissions:
    contents: read
    packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/ndi-do/2024-bergerie-front:${{ github.sha }}
          provenance: false
  update-yaml:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ndi-do/infrastructure
          ref: main
          token: ${{ secrets.PAT }}
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: Update deployment.yaml
        env:
          VERSION: ${{ github.sha }} 
        run: |
          echo "Déploiement de la version $VERSION"
          yq -ie ".ndi-front.image.tag = \"$VERSION\"" applications/front/helm/values.yaml
      - name: Commit changes          
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add applications/front/helm/values.yaml
          git commit -m "Deploying the $VERSION version"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          VERSION: ${{ github.sha }}
        