name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push to Docker registry
    permissions:
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ndi-do/2024-bergerie-front

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      if: github.ref == 'refs/heads/ci_test'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      if: github.ref == 'refs/heads/ci_test'
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      if: github.ref == 'refs/heads/ci_test'
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
